### PR TITLE
Update vendorsetup.sh

### PR DESCRIPTION
**Pull request by MrDuartePT**
The change i made allow compiling the OrangeFox 12.1
https://github.com/MrDuartePT/OrangeFox-Avicii-builder/releases/tag/6516956879
I tested on my device and is working fine

### CODE REVIEW

**Comment by sreeshankark** [comment]
There isn't a Orangefox Recovery 12.1 release. The fox_12.1 is just the branch name given by the Orangefox dev instead of android-12.1. 

Read this: https://wiki.orangefox.tech/en/dev/building#:~:text=The%20version%20number%20of%20the%20build%20manifest%20is%20a%20very%20different%20thing%20from%20the%20OrangeFox%20release%20version%20numbers

Also why are you trying to mess up the flags?
I already gave the correct one: 
https://gitlab.com/OrangeFox/vendor/recovery/-/blob/fox_12.1/orangefox_build_vars.txt?ref_type=heads#:~:text=OF_AB_DEVICE_WITH_RECOVERY_PARTITION

And I didn't dropped the maintainance of OrangeFox Recovery for avicii. Trying to take over the maintainership without any contributions?

I made the OrangeFox and PitchBlack recovery to boot on avicii and it is now supported for all roms.

The contribution and hardwork on this recovery from my side large and I don't want to drop it. So, you better leave it.

Thank you.

**Comment by MrDuartePT** [comment]
I change the OF_MAINTAINER just to build OrangeFox Builder github action and forget to revert.
About the OF_AB_DEVICE_WITH_RECOVERY was a mistake of my part are only should have changed OF_AB_DEVICE to FOX_AB_DEVICE since the old one is deprecated.
I also know the version is different from the tag I just what verify if the vendorsetup.sh is still valid from new version of OrangeFox.

Sorry if this PR look that I'm disrespecting your work it wasn't my intention.

EDIT: See if everything is alright now
https://github.com/sreeshankark/android_device_oneplus_avicii-orangefox/compare/android-12.1...MrDuartePT:android_device_oneplus_avicii:android-12.1

**Comment by sreeshankark** [comment]
I build the previous recoveries with same version which is R11.1. OrangeFox Recovery 12.1 isn't released yet. If you have doubt check the official download section of OrangeFox Recovery The manifest is 12.1 not the OrangeFox Recovery. OrangeFox Recovery latest version is R11.1. And it is based on android-12.1 or fox_12.1. If you need you can PR with the fix for deprecated flag. The version isn't allowed to update.

**Comment by MrDuartePT** [comment]
Ok I get now. I made a new PR is as a draft because I will also add a github action to build the recovery. 
It base on this: https://github.com/xeroxero8x/OrangeFox-Action-Builder

**Pull request closed without merging**
